### ISSUE TITLE
ModuleNotFoundError: No module named 'common'

### ISSUE THREAD

**Issue by KenGeng** [zzcoolj/GNEG#1]
Hi, thanks for sharing your codes in github. But when I clone your repo and try to run the  'all_in_one.py', I get an error:
ModuleNotFoundError: No module named 'common'.

In your source code, I find you add a line "sys.path.insert(0, '../common/')" before importing 'common', but I can not find it in this repo. So, could you please give me any advice?

Best.

**Comment by zzcoolj** [comment]
Hi KenGeng,
Thank you for your feedback. My fault, I forgot to make it public. Please check it now in my repositories.
Best,

**Comment by KenGeng** [comment]
Great! Thanks a lot for your help!
